# Generated by Django 5.1.6 on 2025-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_remove_order_food_item_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="menu.fooditem"),
        ),
    ]
