# Generated by Django 5.1.6 on 2025-06-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0007_order_quantity_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
    ]
